### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.

### ISSUE THREAD

**Issue by diimpp** [WalshyDev/cf-pages-await#13]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

![image](https://user-images.githubusercontent.com/870747/215192283-18f1813c-6d8c-4e94-854f-f2097aadb23b.png)

**Comment by jasongitmail** [comment]
It looks like [updating @actions/core from 1.6](https://github.com/WalshyDev/cf-pages-await/blob/main/package.json#L13 ) to 1.10 might solve this, because the method being called is the same, just [the implementation in @actions/core changed to use the new recommended approach](https://github.com/actions/toolkit/blob/e26febd9886a792d9d30aa907f621157df0058e3/packages/core/src/core.ts#L192).
